name: Build and push image

on:
  workflow_dispatch:

env:
  repo: create-ethernet-map

jobs:
  build-image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: write
    steps:
      # to help build against other platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker-provided build framework to build against other platforms
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.repo }}/Dockerfile
          platforms: linux/amd64
          pull: true
          push: true
          tags: ghcr.io/asrinivasantt/create-ethernet-map:latest
      
      - name: Create container to extract artifact from
        run: docker create --name=temp_container ghcr.io/asrinivasantt/create-ethernet-map:latest
      
      - name: Copy artifact from container
        run: docker cp temp_container:/bin/create-ethernet-map .

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: create-ethernet-map
          name: create-ethernet-map
          tag_name: latest

