name: Build and push image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        arch: [wormhole_b0, blackhole]
        repo: [tt-umd]
    steps:
      # to help build against other platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker-provided build framework to build against other platforms
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.repo }}/Dockerfile
          platforms: linux/amd64
          pull: true
          push: true
          build-args: 'ARCH_NAME=${{ matrix.arch }}'
          tags: ghcr.io/asrinivasantt/sw-hello-world/${{ matrix.repo }}-hello-world:latest-${{ matrix.arch }}
